[default]
contracts = 'contracts'          # The source directory
libs = ['modules']               # A list of library directories
solc_version = '0.8.7'           # Override for the solc version (setting this ignores `auto_detect_solc`)
offline = true                   # Disable downloading of missing solc version(s)
optimizer = true                 # Enable or disable the solc optimizer
optimizer_runs = 200             # The number of optimizer runs
verbosity = 3                    # The verbosity of tests
invariant_runs = 10000           # The number of calls to make in the invariant tests
invariant_depth = 10             # The number of times to run the invariant tests
invariant_call_override = false  # Override calls
invariant_fail_on_revert = true  # Fail the test if the contract reverts

[local]
fuzz_runs = 100

[deep]
fuzz_runs = 500

[super_deep]
fuzz_runs = 50000
